# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cross_orm.proto

require 'google/protobuf'


descriptor_data = "\n\x0f\x63ross_orm.proto\x12\x14org.example.crossorm\"$\n\x07NewUser\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\x05\"-\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x32\x9c\x01\n\x08\x43rossORM\x12\x45\n\x07GetUser\x12\x1c.org.example.crossorm.UserID\x1a\x1a.org.example.crossorm.User\"\x00\x12I\n\nCreateUser\x12\x1d.org.example.crossorm.NewUser\x1a\x1a.org.example.crossorm.User\"\x00\x42\x02P\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Org
  module Example
    module Crossorm
      NewUser = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("org.example.crossorm.NewUser").msgclass
      UserID = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("org.example.crossorm.UserID").msgclass
      User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("org.example.crossorm.User").msgclass
    end
  end
end
